@baseUrl=http://localhost:5000

###
POST {{baseUrl}}/products/
Accept:application/json
Content-Type:application/json

{
  "Name":"Product 1",
  "Description":"Description Product 1",
  "Category":["Cat 1","Cat 2"],
  "ImageFile":"ImageFile  Product 1",
  "Price":102
}