###
GET {{baseUrl}}/products
Accept:application/json

###
GET {{baseUrl}}/products/0191982c-59a7-451b-8d0d-a830bb5ff37a
Accept:application/json

###
GET {{baseUrl}}/products/category/Cat2
Accept:application/json

###
POST {{baseUrl}}/products/
Accept:application/json
Content-Type:application/json

{
  "Name":"",
  "Description":"Description Product 2",
  "Category":["Cat1","Cat2"],
  "ImageFile":"ImageFile  Product 2",
  "Price":187
}

###
PUT {{baseUrl}}/products/
Accept:application/json
Content-Type:application/json

 {
      "id": "0191982c-59a7-451b-8d0d-a830bb5ff37a",
      "name": "Product 1",
      "description": "Description Product 1",
      "category": [
        "Cat1",
        "Cat2"
      ],
      "imageFile": "ImageFile  Product 1",
      "price": 102
}

###
DELETE {{baseUrl}}/products/0191992a-0cc0-40e9-98a9-a3557835cb58
Accept:application/json