###
GET {{baseUrl}}/basket-service/Health
Accept: applciation/json

###
GET {{baseUrl}}/basket-service/basket/assaad
Accept: applciation/json

###
DELETE {{baseUrl}}/basket-service/basket/assaad
Accept: applciation/json

###
POST {{baseUrl}}/basket-service/basket/
Accept:application/json
Content-Type:application/json

{
   "Cart":{
      "UserName":"assaad",
      "Items":[
         {
            "Quantity":2,
            "Color":"Red",
            "Price":700,
            "ProductId":"0191982c-59a7-451b-8d0d-a830bb5ff37a",
            "ProductName":"IPhone X"
         },
         {
            "Quantity":5,
            "Color":"Blue",
            "Price":500,
            "ProductId":"0191982c-59a7-451b-8d0d-a830bb5ff37b",
            "ProductName":"IPhone 12"
         }
      ]
   }
}

###
POST {{baseUrl}}/basket-service/basket/checkout
Accept:application/json
Content-Type:application/json

{
   "CheckOutBasketDto":{
      "userName":"assaad",
      "customerId":"189dc8dc-990f-48e0-a37b-e6f2b60b9d7d",
      "firstName":"john",
      "lastName":"doe",
      "emailAddress":"john@gmail.com",
      "addressLine":"Broadway No:1",
      "country":"England",
      "state":"Nottingham",
      "zipCode":"08050",
      "cardName":"john",
      "cardNumber":"8885555555554444",
      "expiration":"06/30",
      "cvv":"222",
      "paymentMethod":2
   }
}